### ISSUE TITLE
No.1

### ISSUE THREAD

**Issue by MohammedSDev** [n0obs73r/YumYum#1]
Hi 

Here you should not use !! after user input function that return nullable. 
instead use `toIntOrNull` function and handle null value with default number or show user an error message..it is up to you
https://github.com/n0obs73r/YumYum/blob/eaf9559a8d05a70a6d0ba68fc3faa541b51becdb/src/loginActivity.kt#L17

https://github.com/n0obs73r/YumYum/blob/eaf9559a8d05a70a6d0ba68fc3faa541b51becdb/src/Admin.kt#L39

and Don't, don't trust in user input data..always check it( user input could be string, special characters..ext )
https://github.com/n0obs73r/YumYum/blob/eaf9559a8d05a70a6d0ba68fc3faa541b51becdb/src/Chef.kt#L38

 `userType` is a good way to deal with requirements like this...but 
as this intended to OOP rightNow, you have to remove `userType` key and and stick with class type to determine which person type is this 

https://github.com/n0obs73r/YumYum/blob/eaf9559a8d05a70a6d0ba68fc3faa541b51becdb/src/loginActivity.kt#L41

also you will use `class` here and  Chef,User. all of them must extend from Person class.
and don't forgot..sharing actions and properties should be in Person class.

https://github.com/n0obs73r/YumYum/blob/eaf9559a8d05a70a6d0ba68fc3faa541b51becdb/src/Admin.kt#L1

Finally it is good practice to have one center thats is responsible for you data...you can keep them separate (orders, persons, Menus ..ext) but have all of them inside one class that all app classes must deal with it when they need a data.

**Comment by n0obs73r** [comment]
Hello Mohammed, 
I did some changes according to your suggetions. Hope this is fine now!
